---
functional:
  - Возможность регистрации пользователя с помощью элетронной почты
  - Возможность авторизации пользователя с помощью Github
  - Возможность авторизации пользователя с помощью Discord
  - Пользователь должен иметь возможность выбрать игру по уровню сложности
  - Пользователь должен иметь возможность приглашать в игру других пользователей
  - Пользователь должен иметь возможность выбрать игру с ботом
  - Пользователь должен иметь возможность создавать игру по индивидуальному сценарию
  - Пользователь должен иметь возможность во время игры видеть редактор с кодом у другого игрока, а также менять язык программирования во время решения
  - Пользователь должен иметь возможность общаться в чате игры с другими пользователями
  - Пользователь должен иметь возможность просматривать рейтинг участников за неделю, месяц и за все время
  - Пользователь должен иметь возможность просматривать запись завершенной игры
  - Пользователь должен иметь возможность менять язык задач
  - Пользователь должен иметь возможность выбирать в настройках тип и уровень звука
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность просматривать историю своих игр, а также игр других пользователей сайта
  - Пользователь должен иметь возможность подписываться на других пользователей
  - Пользователь не должен иметь возможность редактировать код в завершенной игре
